// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entrys (
    owner, ammount
)VALUES($1,$2)
RETURNING id, owner, ammount, created_at, updated_at
`

type CreateEntryParams struct {
	Owner   string `json:"owner"`
	Ammount int64  `json:"ammount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.Owner, arg.Ammount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Ammount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
