// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Entry struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
	// must be positive
	Ammount   int64     `json:"ammount"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
